version: "3"

services: 
  first_server:
    container_name: first_server_d
    restart: always
    build:
      context: ./server
    ports:
      - 3333
    environment:
      - PORT=3333
      - NAME=APP_1
    networks:
      - node_nginx_net
  
  second_server:
    container_name: second_server_d
    restart: always
    build:
      context: ./server
    ports:
      - 4444
    environment:
      - PORT=4444
      - NAME=APP_2
    networks:
      - node_nginx_net
  
  nginx:
    container_name: node_nginx
    image: nginx
    restart: always
    volumes: 
      - './nginx.conf:/etc/nginx/conf.d/default.conf'
    ports: 
      - 80:80
      - 90:90
    networks:
      - node_nginx_net

  portainer:
    image: portainer/portainer
    command: -H unix:///var/run/docker.sock
    restart: always
    ports:
      - 9000:9000
      - 8000:8000
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer_data:/data
    networks:
      - node_nginx_net

networks:
  node_nginx_net:
    driver: bridge

volumes:
  portainer_data:
